version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/local"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"