/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /**
     * Get health status 
     * @description Returns OK if the validator considers itself healthy.
     */
    get: operations["health"];
  };
  "/version": {
    /**
     * Get version information 
     * @description Returns version information about the validator daemon.
     */
    get: operations["version"];
  };
  "/query": {
    /**
     * Query the network 
     * @description Returns the results of a SQL read query against the Tableland network
     */
    get: operations["queryByStatement"];
    /**
     * Query the network (POST) 
     * @description Returns the results of a SQL read query against the Tableland network
     */
    post: operations["queryByStatementPost"];
  };
  "/receipt/{chainId}/{transactionHash}": {
    /**
     * Get transaction status 
     * @description Returns the status of a given transaction receipt by hash
     */
    get: operations["receiptByTransactionHash"];
  };
  "/tables/{chainId}/{tableId}": {
    /**
     * Get table information 
     * @description Returns information about a single table, including schema information
     */
    get: operations["getTableById"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Table: {
      /** @example healthbot_80002_1 */
      name?: string;
      /** @example https://testnets.tableland.network/api/v1/tables/80002/1 */
      external_url?: string;
      /** @example https://tables.testnets.tableland.xyz/80002/1.html */
      animation_url?: string;
      /** @example https://tables.testnets.tableland.xyz/80002/1.svg */
      image?: string;
      /**
       * @example {
       *   "display_type": "date",
       *   "trait_type": "created",
       *   "value": 1657113720
       * }
       */
      attributes?: ({
          /** @description The display type for marketplaces */
          display_type?: string;
          /** @description The trait type for marketplaces */
          trait_type?: string;
          /** @description The value of the property */
          value?: string | number | boolean | Record<string, never>;
        })[];
      schema?: components["schemas"]["Schema"];
    };
    TransactionReceipt: {
      /**
       * @deprecated 
       * @description This field is deprecated 
       * @example 1
       */
      table_id?: string;
      /**
       * @example [
       *   "1",
       *   "2"
       * ]
       */
      table_ids?: (string)[];
      /** @example 0x02f319429b8a7be1cbb492f0bfbf740d2472232a2edadde7df7c16c0b61aa78b */
      transaction_hash?: string;
      /**
       * Format: int64 
       * @example 27055540
       */
      block_number?: number;
      /**
       * Format: int32 
       * @example 80002
       */
      chain_id?: number;
      /** @example The query statement is invalid */
      error?: string;
      /**
       * Format: int32 
       * @example 1
       */
      error_event_idx?: number;
    };
    Schema: {
      columns?: (components["schemas"]["Column"])[];
      /**
       * @example [
       *   "PRIMARY KEY (id)"
       * ]
       */
      table_constraints?: (string)[];
    };
    Column: {
      /** @example id */
      name?: string;
      /** @example integer */
      type?: string;
      /**
       * @example [
       *   "NOT NULL",
       *   "PRIMARY KEY",
       *   "UNIQUE"
       * ]
       */
      constraints?: (string)[];
    };
    VersionInfo: {
      /** @example 79688910d4689dcc0991a0d8eb9d988200586d8f */
      git_commit?: string;
      /** @example foo/experimentalfeature */
      git_branch?: string;
      /** @example dirty */
      git_state?: string;
      /** @example v1.2.3_dirty */
      git_summary?: string;
      /** @example 2022-11-29T16:28:04Z */
      build_date?: string;
      /** @example v1.0.1 */
      binary_version?: string;
    };
    Query: {
      /**
       * @description The SQL read query statement 
       * @example select * from healthbot_80002_1
       */
      statement?: string;
      /**
       * @description The requested response format: * `objects` - Returns the query results as a JSON array of JSON objects. * `table` - Return the query results as a JSON object with columns and rows properties.
       *  
       * @example objects
       */
      format?: string;
      /**
       * @description Whether to extract the JSON object from the single property of the surrounding JSON object. 
       * @example false
       */
      extract?: boolean;
      /**
       * @description Whether to unwrap the returned JSON objects from their surrounding array. 
       * @example false
       */
      unwrap?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /**
   * Get health status 
   * @description Returns OK if the validator considers itself healthy.
   */
  health: {
    responses: {
      /** @description The validator is healthy. */
      200: never;
    };
  };
  /**
   * Get version information 
   * @description Returns version information about the validator daemon.
   */
  version: {
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["VersionInfo"];
        };
      };
    };
  };
  /**
   * Query the network 
   * @description Returns the results of a SQL read query against the Tableland network
   */
  queryByStatement: {
    parameters: {
      query: {
        /**
         * @description The SQL read query statement 
         * @example select * from healthbot_80002_1
         */
        statement: string;
        /**
         * @description The requested response format:
         *  * `objects` - Returns the query results as a JSON array of JSON objects.
         *  * `table` - Return the query results as a JSON object with columns and rows properties.
         */
        format?: "objects" | "table";
        /** @description Whether to extract the JSON object from the single property of the surrounding JSON object. */
        extract?: boolean;
        /** @description Whether to unwrap the returned JSON objects from their surrounding array. */
        unwrap?: boolean;
      };
    };
    responses: {
      /** @description Successful operation */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Invalid query/statement value */
      400: never;
      /** @description Row Not Found */
      404: never;
      /** @description Too Many Requests */
      429: never;
    };
  };
  /**
   * Query the network (POST) 
   * @description Returns the results of a SQL read query against the Tableland network
   */
  queryByStatementPost: {
    /** @description A JSON containing the statement and additional options */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Query"];
      };
    };
    responses: {
      /** @description Successful operation */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Invalid query/statement value */
      400: never;
      /** @description Row Not Found */
      404: never;
      /** @description Too Many Requests */
      429: never;
    };
  };
  /**
   * Get transaction status 
   * @description Returns the status of a given transaction receipt by hash
   */
  receiptByTransactionHash: {
    parameters: {
      path: {
        /**
         * @description The parent chain to target 
         * @example 80002
         */
        chainId: number;
        /**
         * @description The transaction hash to request 
         * @example 0x02f319429b8a7be1cbb492f0bfbf740d2472232a2edadde7df7c16c0b61aa78b
         */
        transactionHash: string;
      };
    };
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["TransactionReceipt"];
        };
      };
      /** @description Invalid chain identifier or transaction hash format */
      400: never;
      /** @description No transaction receipt found with the provided hash */
      404: never;
      /** @description Too Many Requests */
      429: never;
    };
  };
  /**
   * Get table information 
   * @description Returns information about a single table, including schema information
   */
  getTableById: {
    parameters: {
      path: {
        /**
         * @description The parent chain to target 
         * @example 80002
         */
        chainId: number;
        /**
         * @description Table identifier 
         * @example 1
         */
        tableId: string;
      };
    };
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Table"];
        };
      };
      /** @description Invalid chain or table identifier */
      400: never;
      /** @description Table Not Found */
      404: never;
      /** @description Too Many Requests */
      429: never;
      /** @description Internal Server Error */
      500: never;
    };
  };
}
